server:
  port: 8081
  
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/willywonkafactory_db
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create
    show-sql: false